/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignmentjudge;

import TesterCode.Tester;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sunil
 */
public class Menu extends javax.swing.JFrame {
    
    
    private int xpos;
    private int ypos;
    /**
     * Creates new form Menu
     */
    private String username;
    private String password;
    public Menu() {
        initComponents();
        backgroundlbl.setFocusable(true);
    }
    public Menu(String usrname, String pass)
    {
        this.username = usrname;
        this.password = pass;
        initComponents();
        backgroundlbl.setFocusable(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exiticn = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        download_attachmentslbl = new javax.swing.JLabel();
        createcasesicnlbl = new javax.swing.JLabel();
        evaluatelbl = new javax.swing.JLabel();
        reporticnlbl = new javax.swing.JLabel();
        viewcsvicn = new javax.swing.JLabel();
        casebuilderlbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        reportlbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        viewcsvlbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        createcaseslbl = new javax.swing.JLabel();
        SideMenu = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        backgroundlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assignment Judge");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1160, 10));

        exiticn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close_1.png"))); // NOI18N
        exiticn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exiticnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exiticnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exiticnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exiticnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exiticnMouseReleased(evt);
            }
        });
        getContentPane().add(exiticn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, -1, -1));

        MenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WorkFlow", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        MenuPanel.setForeground(new java.awt.Color(255, 255, 255));
        MenuPanel.setToolTipText("");
        MenuPanel.setName(""); // NOI18N
        MenuPanel.setOpaque(false);

        download_attachmentslbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        download_attachmentslbl.setForeground(new java.awt.Color(255, 255, 255));
        download_attachmentslbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/download_workflow.png"))); // NOI18N
        download_attachmentslbl.setText("Step 1:-Download attachments ");
        download_attachmentslbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                download_attachmentslblMouseClicked(evt);
            }
        });

        createcasesicnlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/testcases.png"))); // NOI18N
        createcasesicnlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createcasesicnlblMouseClicked(evt);
            }
        });

        evaluatelbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        evaluatelbl.setForeground(new java.awt.Color(255, 255, 255));
        evaluatelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/evaluate .png"))); // NOI18N
        evaluatelbl.setText("   Step 3:-Evaluate Assignments");
        evaluatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluatelblMouseClicked(evt);
            }
        });

        reporticnlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/report.png"))); // NOI18N
        reporticnlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporticnlblMouseClicked(evt);
            }
        });

        viewcsvicn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        viewcsvicn.setForeground(new java.awt.Color(255, 255, 255));
        viewcsvicn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/generate_csv.png"))); // NOI18N
        viewcsvicn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewcsvicnMouseClicked(evt);
            }
        });

        casebuilderlbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        casebuilderlbl.setForeground(new java.awt.Color(255, 255, 255));
        casebuilderlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/unitcasebuider.png"))); // NOI18N
        casebuilderlbl.setText("Step 4:-Unit Test Buider");
        casebuilderlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casebuilderlblMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow_down(white).png"))); // NOI18N

        jLabel11.setForeground(new java.awt.Color(102, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow_down(white).png"))); // NOI18N

        reportlbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        reportlbl.setForeground(new java.awt.Color(255, 255, 255));
        reportlbl.setText("Step 4:-Cumulative Report");
        reportlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportlblMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow_down(white).png"))); // NOI18N

        viewcsvlbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        viewcsvlbl.setForeground(new java.awt.Color(255, 255, 255));
        viewcsvlbl.setText("Step 4:View CSV");
        viewcsvlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewcsvlblMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/right_arrow(white).png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow_left(white).png"))); // NOI18N

        createcaseslbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createcaseslbl.setForeground(new java.awt.Color(255, 255, 255));
        createcaseslbl.setText("Step 2:-Create test cases");
        createcaseslbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createcaseslblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addComponent(createcaseslbl)
                        .addGap(4, 4, 4)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(download_attachmentslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(evaluatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(createcasesicnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addComponent(casebuilderlbl)
                .addGap(10, 10, 10)
                .addComponent(jLabel15)
                .addGap(20, 20, 20)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(reporticnlbl))
                    .addComponent(reportlbl))
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(viewcsvicn))
                    .addComponent(viewcsvlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(createcaseslbl))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel9))
                    .addComponent(download_attachmentslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(createcasesicnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(evaluatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(casebuilderlbl))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reporticnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(reportlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewcsvicn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(viewcsvlbl))))
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 900, 500));

        SideMenu.setBackground(new java.awt.Color(255, 255, 255));
        SideMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        SideMenu.setForeground(new java.awt.Color(255, 255, 255));
        SideMenu.setOpaque(false);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(184, 42, 96));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/aboutus.png"))); // NOI18N
        jButton2.setText(" About Us             ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(184, 42, 96));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/documentation.png"))); // NOI18N
        jButton3.setText("Documentation  ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(184, 42, 96));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/credits.png"))); // NOI18N
        jButton4.setText("Acknowlegement");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideMenuLayout = new javax.swing.GroupLayout(SideMenu);
        SideMenu.setLayout(SideMenuLayout);
        SideMenuLayout.setHorizontalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addContainerGap())
        );
        SideMenuLayout.setVerticalGroup(
            SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(SideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 220));

        backgroundlbl.setForeground(new java.awt.Color(255, 255, 255));
        backgroundlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background(bg5).png"))); // NOI18N
        backgroundlbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundlblMouseDragged(evt);
            }
        });
        backgroundlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundlblMousePressed(evt);
            }
        });
        getContentPane().add(backgroundlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exiticnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseClicked
        int i = JOptionPane.showConfirmDialog(this,
                        "Are you sure to exit?", "Closing Dialog",
                        JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
                    this.dispose();
        }
    }//GEN-LAST:event_exiticnMouseClicked

    private void exiticnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseEntered
        ImageIcon icn = new ImageIcon(getClass().getResource("/resources/closeho.png"));
        exiticn.setIcon(icn);
    }//GEN-LAST:event_exiticnMouseEntered

    private void exiticnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseExited
        ImageIcon icn = new ImageIcon(getClass().getResource("/resources/close_1.png"));
        exiticn.setIcon(icn);
    }//GEN-LAST:event_exiticnMouseExited

    private void exiticnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMousePressed
        ImageIcon icn = new ImageIcon(getClass().getResource("/resources/closec.png"));
        exiticn.setIcon(icn);
    }//GEN-LAST:event_exiticnMousePressed

    private void exiticnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseReleased
        
    }//GEN-LAST:event_exiticnMouseReleased

    private void download_attachmentslblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_download_attachmentslblMouseClicked
        new Download_Attachments(username, password).setVisible(true);
    }//GEN-LAST:event_download_attachmentslblMouseClicked

    private void createcasesicnlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createcasesicnlblMouseClicked
        new create_cases().setVisible(true);
    }//GEN-LAST:event_createcasesicnlblMouseClicked

    private void casebuilderlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casebuilderlblMouseClicked
        new UnitCaseBuilder().setVisible(true);
    }//GEN-LAST:event_casebuilderlblMouseClicked

    private void reporticnlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporticnlblMouseClicked
        new Cumulative_Report().setVisible(true);
    }//GEN-LAST:event_reporticnlblMouseClicked

    private void createcaseslblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createcaseslblMouseClicked
        new UnitCaseBuilder().setVisible(true);
    }//GEN-LAST:event_createcaseslblMouseClicked

    private void reportlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportlblMouseClicked
        new Cumulative_Report().setVisible(true);
    }//GEN-LAST:event_reportlblMouseClicked

    private void evaluatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluatelblMouseClicked
       new eval_form_lbl().setVisible(true);
    }//GEN-LAST:event_evaluatelblMouseClicked

    private void viewcsvlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewcsvlblMouseClicked
        File file = new File(AssignmentJudge.workingDirectory + "\\" + "resultCSV.csv");
        try {
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewcsvlblMouseClicked

    private void viewcsvicnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewcsvicnMouseClicked
        File file = new File(AssignmentJudge.workingDirectory + "\\" + "resultCSV.csv");
        try {
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewcsvicnMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         new About_us().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        URL url = null;
        try {
            url = new URL("https://hopeful-lewin-d29d65.netlify.com/assignmentjudge/module-summary");
        } catch (MalformedURLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        Browse.openWebpage(url);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Credits().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void backgroundlblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundlblMousePressed
        xpos = evt.getX();
        ypos = evt.getY();
    }//GEN-LAST:event_backgroundlblMousePressed

    private void backgroundlblMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundlblMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xpos, y - ypos);
    }//GEN-LAST:event_backgroundlblMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel SideMenu;
    private javax.swing.JLabel backgroundlbl;
    private javax.swing.JLabel casebuilderlbl;
    private javax.swing.JLabel createcasesicnlbl;
    private javax.swing.JLabel createcaseslbl;
    private javax.swing.JLabel download_attachmentslbl;
    private javax.swing.JLabel evaluatelbl;
    private javax.swing.JLabel exiticn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel reporticnlbl;
    private javax.swing.JLabel reportlbl;
    private javax.swing.JLabel viewcsvicn;
    private javax.swing.JLabel viewcsvlbl;
    // End of variables declaration//GEN-END:variables
}
