/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignmentjudge;

import javax.swing.ImageIcon;
import UnitTester.BuildUnitTestCasesFile;
import javax.swing.JOptionPane;

/**
 *
 * @author Sunil
 */
public class UnitCaseBuilder extends javax.swing.JFrame {
    
    	private static final String unitTestCaseFileName = "unitTestCases";
	private static final String unitExpectedOutputFileName = "expectedUnitTestOutput";
	private static final String unitProgramOutputFileName = "programUnitTestOutput";
        
        
        public static String getUnitTestCaseFileName() {return unitTestCaseFileName;}
	public static String getUnitExpectedOutputFileName() {return unitExpectedOutputFileName;}
	public static String getUnitProgramOutputFileName() {return unitProgramOutputFileName;}
    /**
     * Creates new form UnitCaseBuilder
     */
    public UnitCaseBuilder() {
        initComponents();
        backgroundlbl.setFocusable(true);
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        unitExpectedOutputField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        targetFunctionName = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        unitTestCaseField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        exiticn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buildbtn = new javax.swing.JButton();
        backgroundlbl = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unitExpectedOutputField.setColumns(20);
        unitExpectedOutputField.setRows(5);
        jScrollPane1.setViewportView(unitExpectedOutputField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 440, -1));

        targetFunctionName.setColumns(20);
        targetFunctionName.setForeground(new java.awt.Color(153, 153, 153));
        targetFunctionName.setRows(5);
        targetFunctionName.setText("For object foo(int a, int b) Enter as: foo, int, int");
        targetFunctionName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                targetFunctionNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                targetFunctionNameFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(targetFunctionName);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 440, 90));

        unitTestCaseField.setColumns(20);
        unitTestCaseField.setForeground(new java.awt.Color(153, 153, 153));
        unitTestCaseField.setRows(5);
        unitTestCaseField.setText("For object foo(int a, int b) Enter as: 5, 6");
        unitTestCaseField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unitTestCaseFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unitTestCaseFieldFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(unitTestCaseField);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 440, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assignment Judge");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UnitCase Builder");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, 30));

        exiticn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close_1.png"))); // NOI18N
        exiticn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exiticnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exiticnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exiticnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exiticnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exiticnMouseReleased(evt);
            }
        });
        getContentPane().add(exiticn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Unit Test Case");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Expected Output");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 20));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Function Signature to unit case");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        buildbtn.setBackground(new java.awt.Color(255, 255, 255));
        buildbtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buildbtn.setForeground(new java.awt.Color(184, 42, 96));
        buildbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/click_evaluate.png"))); // NOI18N
        buildbtn.setText("Build Unit Test ");
        buildbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildbtnActionPerformed(evt);
            }
        });
        getContentPane().add(buildbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 230, 40));

        backgroundlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background(bg).png"))); // NOI18N
        getContentPane().add(backgroundlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 510));

        messageLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        getContentPane().add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 280, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exiticnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseClicked
        this.dispose();
    }//GEN-LAST:event_exiticnMouseClicked

    private void exiticnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseEntered
        ImageIcon icn = new ImageIcon(getClass().getResource("/resources/closeho.png"));
        exiticn.setIcon(icn);
    }//GEN-LAST:event_exiticnMouseEntered

    private void exiticnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseExited
        ImageIcon icn = new ImageIcon(getClass().getResource("/resources/close_1.png"));
        exiticn.setIcon(icn);
    }//GEN-LAST:event_exiticnMouseExited

    private void exiticnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMousePressed
        ImageIcon icn = new ImageIcon(getClass().getResource("/resources/closec.png"));
        exiticn.setIcon(icn);
    }//GEN-LAST:event_exiticnMousePressed

    private void exiticnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticnMouseReleased

    }//GEN-LAST:event_exiticnMouseReleased

    private void buildbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildbtnActionPerformed
        if(unitTestCaseField.getText().equals("For object foo(int a, int b) Enter as: 5, 6")){
            JOptionPane.showMessageDialog(this, "Unit Test Case Field can't be empty!");
        }
        else if(unitExpectedOutputField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Expected Output Field can't be empty!");
        }
        else if(targetFunctionName.getText().equals("For object foo(int a, int b) Enter as: foo, int, int")){
            JOptionPane.showMessageDialog(null, "Target Function Field can't be empty!");
        }
        else{
             new BuildUnitTestCasesFile(
				unitTestCaseFileName,
				unitExpectedOutputFileName,
				unitProgramOutputFileName,
				targetFunctionName.getText(),
				unitTestCaseField.getText(),
				unitExpectedOutputField.getText(),
				messageLabel
				);
        }
    }//GEN-LAST:event_buildbtnActionPerformed

    private void unitTestCaseFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unitTestCaseFieldFocusGained
        if(unitTestCaseField.getText().equals("For object foo(int a, int b) Enter as: 5, 6"))
        {
            unitTestCaseField.setText("");
            unitTestCaseField.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_unitTestCaseFieldFocusGained

    private void unitTestCaseFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unitTestCaseFieldFocusLost
        if(unitTestCaseField.getText().trim().equals(""))
        {
            unitTestCaseField.setText("For object foo(int a, int b) Enter as: 5, 6");
            unitTestCaseField.setForeground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_unitTestCaseFieldFocusLost

    private void targetFunctionNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_targetFunctionNameFocusGained
       if(targetFunctionName.getText().equals("For object foo(int a, int b) Enter as: foo, int, int"))
        {
            targetFunctionName.setText("");
            targetFunctionName.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_targetFunctionNameFocusGained

    private void targetFunctionNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_targetFunctionNameFocusLost
        if(targetFunctionName.getText().trim().equals(""))
        {
            targetFunctionName.setText("For object foo(int a, int b) Enter as: foo, int, int");
            targetFunctionName.setForeground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_targetFunctionNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitCaseBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitCaseBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitCaseBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitCaseBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitCaseBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundlbl;
    private javax.swing.JButton buildbtn;
    private javax.swing.JLabel exiticn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea targetFunctionName;
    private javax.swing.JTextArea unitExpectedOutputField;
    private javax.swing.JTextArea unitTestCaseField;
    // End of variables declaration//GEN-END:variables
}
